repos:
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: python -m isort
        language: system
        types: [python]

    -   id: autopep8
        name: autopep8
        entry: python -m autopep8 --in-place
        language: system
        types: [python]

    -   id: mypy
        name: mypy
        entry: python -m mypy --explicit-package-bases .
        language: system
        pass_filenames: false

    -   id: unittest
        name: unittest
        entry: python -m unittest discover -s ./tests -p *.py
        language: system
        pass_filenames: false
        